### ISSUE TITLE
No logs

### ISSUE THREAD

**Issue by m3tal** [akayn/kbMon#2]

**Comment by m3tal** [comment]
Kbmon is not saving any logs in windows/logs directory

**Comment by akayn** [comment]
this project is no longer maintained, and is only kept as a reference for developers who wants to write complex device drivers. 
however, the log should be saved to \\SystemRoot\\Logs\\HomeGroup\\klog.txt as written at https://github.com/akayn/kbMon/blob/master/Iliad/src/Driver.c#L761 

best regards i will be closing this issue now.
